---
- name: Set hostname
  hostname: name={{ hostname }}

- name: Append hostname to /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1\tlocalhost {{ hostname }}'

- name: Append inventory to /etc/hosts
  lineinfile: dest=/etc/hosts line='{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].hostname }}'
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: groups['boxes']

- name: Update package manager cache
  apt: update_cache=yes cache_valid_time="{{ apt_cache_valid_time }}"

- name: Update all packages to the latest version
  apt: upgrade=dist